### ISSUE TITLE
Windows cannot auto launch after application's install path changed.

### ISSUE THREAD

**Issue by lanistor** [Teamwork/node-auto-launch#100] opened 2019-11-05 17:37 UTC
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows): Windows10
- Node version (run `node -v`): 12.2
- auto-launch version: 5.0.5
- The options you're passing to auto-launch:
  ```
  new AutoLaunch({
    name: SystemConfig.EN_NAME,
    mac: {
      useLaunchAgent: true,
    }
  });
  ```
- Are you using NW.js or Electron?
  - If so, which version?
    - Yes, Electron 6.0.2
  - If you're using Electron, are you using auto-launch from the main process or a renderer process?
    - main process
- Can you reproduce this with a simple Hello World example app?
  - sorry, i cannot.
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem?
  - maybe
---

I use electron, at first, i use node x64 to build our app, and it installed in default directory `c:/program file` in all uses' system, and it can auto launch. However, when i change node to x32, it installed in default directory `c:/program file(x86)`, and it cannot auto launch anymore, even i use `disable()` then `enable`.

**Comment by Oxalin** [comment] 2023-12-03 18:45
It is not a bug. The app is registered with a given path when being registered. If this path is changed, Windows, or any other OS, will not be able to find the app where it was registered.

What you would have to do is to support this at the app level if you intend to change from one to the other.

**Comment by Oxalin** [comment] 2024-04-10 05:09
I'll close this issue. Please, reopen it if you can reproduce it or add more info.

**Closed by Oxalin** 2024-04-10 05:09 UTC
