### ISSUE TITLE
release v5.0.2 unusable

### ISSUE THREAD

**Issue by paseo** [Teamwork/node-auto-launch#69] opened 2017-11-14 12:00 UTC
- The target platform(s) the problem occurs on: Mac
- Node version:  v8.8.1
- auto-launch version:  5.0.2
- The options you're passing to auto-launch: Electron v1.4.6  / main process

verify steps:

1. install auto-launch v5.0.2
```
npm install auto-launch@5.0.2
```

2. see auto-launch installed package directory
```
open ./node_modules/auto-launch
```
only 3 files in the package directory: LICENSE.md、package.json、README.md。dist folder lost.

**Comment by ripexz** [comment] 2017-11-14 12:06
Confirmed, you can even see it on https://npm.runkit.com/auto-launch

**Comment by ripexz** [comment] 2017-11-14 12:08
Although I guess this is a duplicate of #67 - closing this one.

**Closed by ripexz** 2017-11-14 12:08 UTC
